name: CI
on:
  pull_request:
    branches: [master, main, develop, feature/**, fix/**]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: setup
        uses: ./.github/workflows/composite/setup
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run test
        env:
          OPENAI_API_ENDPOINT_URL: ${{ secrets.OPENAI_API_ENDPOINT_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: poetry run pytest

  code_lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: setup
        uses: ./.github/workflows/composite/setup
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run ruff check
        run: poetry run ruff --fix .

      - name: Run black check
        run: poetry run black --check .

  type_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: setup
        uses: ./.github/workflows/composite/setup
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run mypy
        run: poetry run mypy . --config-file ./pyproject.toml
