name: Create a pull request and merge for release staging.

on:
  push:
    branches: [master]

jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Check if pr exists
        id: check_pr
        run: |
          pr_title=${{ 'ReleaseStaging' }}
          base_branch=${{ 'release/staging' }}
          echo "::set-output name=count::$(gh pr list -S ${pr_title}' in:title' -B $base_branch | wc -l)"
          echo "::set-output name=pr_title::$pr_title"
          echo "::set-output name=base_branch::$base_branch"
      - name: Create pr
        id: create_pr
        if: ${{ steps.check_pr.outputs.count == 0 }}
        run: pull_request_url=$(gh pr create -B ${{ steps.check_pr.outputs.base_branch }} -t ${{ steps.check_pr.outputs.pr_title }} -b "")
      - name: Merge pr
        run: gh pr merge ${{ steps.create_pr.outputs.pull_request_url }} --merge
